MyAppIADS/urls.py
from django.contrib import admin
from django.urls import path, include
from MyAppIADS import views
from MyAppIADS.views import IndexView, DetailView

app_name = 'MyAppIADS'

urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),
    path(r'about/', views.about, name='about_page'),
    path(r'<int:book_id>/', DetailView.as_view(), name='detail'),
    path(r'findbooks/', views.findbooks, name='findbooks'),
    path(r'placeorder/', views.place_order, name='placeorder'),
    path(r'review/', views.review, name='review'),
    path(r'login/' ,views.user_login, name='login'),
    path(r'logout/',views.user_logout, name='logout'),
    path(r'checkreview/<int:book_id>', views.chk_reviews,name='checkreview'),
    path(r'register/', views.register_member, name='register_member'),
    path(r'myorder/', views.myorders, name='my_order'),
    path(r'userratings/', views.UserRatings, name='User_Ratings'),
    path(r'chk_reviews/<int:book_id>', views.chk_reviews, name='chk_reviews'),
    path(r'checkreviews', views.checkreviews, name='checkreviews'),
    path(r'loginpage/', views.loginpage, name='loginpage'),
    ]

MySiteIADS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from MyAppIADS.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'MyAppIADS/', include('MyAppIADS.urls')),
    path(r'', include('django.contrib.auth.urls')),
    url(r'^$', IndexView.as_view() ,name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyAppIADS/models.py
from django.db import models
import datetime
from django.core.validators import *
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.safestring import mark_safe

class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=False, default='USA')

    def __str__(self):
        return self.name


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('S', 'Scinece&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='S')
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                validators=[MaxValueValidator(1000), MinValueValidator(0)])
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Member(User):
    STATUS_CHOICES = [
        (1, 'Regular member'),
        (2, 'Premium Member'),
        (3, 'Guest Member'),
    ]

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, default='ON')
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True, related_name='bb')
    image = models.ImageField(upload_to='profile_imamge', blank=True)

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" style="width: 200px; height:200px;" />' % self.image.url)
        else:
            return 'No Image Found'
    image_tag.short_description = 'Image'

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Order(models.Model):
    CHOICE = [
        (0, 'Purchase'),
        (1, 'Borrow')
    ]
    member = models.ForeignKey(Member, related_name='MemberOrder', on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, related_name='orderbooks')
    order_type = models.IntegerField(choices=CHOICE, default=1)
    order_date = models.DateField(default=timezone.now)

    def total_items(self):
        return self.books.count()

    def __str__(self):
        return '{} {} {} {} {}'.format(self.member.first_name, self.member.last_name, self.order_date,
                                       self.total_items(), self.pk)


class Review(models.Model):
    reviewer = models.EmailField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    comments = models.TextField(blank=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return '{} {} {}'.format(self.book, self.reviewer, self.rating)

MyAppIADS/forms.py
from django import forms
from django.core.exceptions import ValidationError

from MyAppIADS.models import Order, Review, Member
from django.contrib.gis.db.backends.spatialite import client
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SearchForm(forms.Form):
    CATEGORY_CHOICES = [
        ('S', 'Scinece&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    name = forms.CharField(label='Your Name', max_length=100, required=False)
    category = forms.ChoiceField(label='Select a Category:', widget=forms.RadioSelect, choices=CATEGORY_CHOICES,
                                 required=False)
    max_price = forms.IntegerField(label='Maximum Price', min_value=0, required=True)


class OrderForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #    self.request = kwargs.pop('request')
    #    super(OrderForm, self).__init__(*args, **kwargs)
    #    self.fields['member'].label = "Member name:"
    #    self.fields['member'].initial = self.request.user.username

    class Meta:
        model = Order
        fields = ['books', 'member', 'order_type']
        widgets = {'books': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect}
        # labels = {'member': u'Member name', }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'book', 'rating', 'comments', 'date']
        widgets = {'book': forms.RadioSelect()}
        labels = {'reviewer': u'Please enter a valid email', 'rating': u'Rating: An integer between 1 and 5 '}


class MemberForm(UserCreationForm):
    class Meta:
        model = Member
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    first_name = forms.CharField(label='First Name', max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(label='Last Name', max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(label='Email', max_length=254, help_text='Required. Inform a valid email address.')

MyAppIADS/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import SearchForm, OrderForm, ReviewForm, MemberForm
# Create your views here.
from MyAppIADS.models import Book, Member, Review, Order
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
import random, datetime
from django.views.generic.base import View


def index(request):
    if 'username' in request.session:
        if 'last_login' in request.session:
            last_log = request.session.get('last_login')
        else:
            last_log = "more than one hour ago"
        booklist = Book.objects.all().order_by('pk')[:10]
        member = Member.objects.filter(username=request.session.get('username'))
        image = member.image.url
        return render(request, 'MyApp/index0.html', {'booklist': booklist, 'last_login': last_log})
    else:
        return render(request, 'MyApp/index0.html', {})


def about(request):
    if 'lucky_num' in request.session:
        mynum = request.session.get('lucky_num')
        return render(request, 'MyApp/about.html', {'mynum': mynum})
    else:
        request.session['lucky_num'] = random.randint(1, 101)
        request.session.set_expiry(5 * 60)
        return render(request, 'MyApp/about.html')


class IndexView(View):

    def get(self, request):
                if 'last_login' in request.session:
                    last_log = request.session.get('last_login')
                else:
                    last_log = "more than one hour ago"
                booklist = Book.objects.all().order_by('pk')[:10]
                return render(request, 'MyApp/index0.html', {'booklist': booklist, 'last_login': last_log})


class AboutView(View):

    def get(self, request):
        if request.session.has_key('username'):
            if 'lucky_num' in request.session:
                mynum = request.session.get('lucky_num')
                return render(request, 'MyApp/about.html', {'mynum': mynum})
            else:
                request.session['lucky_num'] = random.randint(1, 101)
                request.session.set_expiry(5 * 60)
                return render(request, 'MyApp/about.html')
        else:
            return render(request, 'MyApp/login.html')


def detail(request, book_id):
    book_Detail = get_object_or_404(Book, id=book_id)
    return render(request, 'MyApp/detail.html',
                  {'book_title': book_Detail.title.upper(), 'book_price': book_Detail.price,
                   'book_publisher': book_Detail.publisher})


class DetailView(View):

    def get(self, request, book_id):
        book_Detail = get_object_or_404(Book, id=book_id)
        id = str(book_id)+'.jpg'
        return render(request, 'MyApp/detail.html',
                      {'book_title': book_Detail.title.upper(), 'book_price': book_Detail.price,
                       'book_publisher': book_Detail.publisher, 'id': id})


def UserRatings(request):
    dictn = {}
    li = []
    for i in range(1, 9):
        B = Book.objects.get(pk=i)
        if B:
            R = Review.objects.filter(book__id=B.id)
            if R:
                total = 0
                i = 0
                for r in R:
                    total += r.rating
                    i += 1
                ave = total / i
                dictn[ave] = B.title
    li = list(dictn.items())
    li.sort(reverse=True)
    return render(request, 'MyApp/UserRatings.html', {'Rating': li})


def findbooks(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            category = form.cleaned_data['category']
            max_price = form.cleaned_data['max_price']
            if category:
                booklist = Book.objects.filter(category=category).filter(price__lte=max_price)
                return render(request, 'MyApp/results.html',
                              {'booklist': booklist, 'name': name, 'category': category, 'max_price': max_price})
            else:
                booklist = Book.objects.filter(price__lte=max_price)
                return render(request, 'MyApp/results.html',
                              {'booklist': booklist, 'name': name, 'max_price': max_price})
        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'MyApp/findbooks.html', {'form': form})


def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            books = form.cleaned_data['books']
            #m = request.session.get('username')
            #member = Member.objects.get(username=m)
            order = form.save()
            member = order.member
            type = order.order_type
            order.save()
            if type == 1:
                for b in order.books.all():
                    member.borrowed_books.add(b)
            return render(request, 'MyApp/order_response.html', {'books': books, 'order': order, })
        else:
            return render(request, 'MyApp/placeorder.html', {'form': form})

    else:
        form = OrderForm()
        return render(request, 'MyApp/placeorder.html', {'form': form})


def review(request):
    status = request.session.get('status')
    if status == 1 or status == 2:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                reviewer = form.cleaned_data['reviewer']
                comments = form.cleaned_data['comments']
                date = form.cleaned_data['date']
                rating = form.cleaned_data['rating']
                review1 = form.save()
                book = review1.book
                book.num_reviews += 1
                book.save()
                booklist = Book.objects.all()
                return render(request, 'MyApp/index0.html', {'booklist': booklist})
            else:
                return render(request, 'MyApp/review.html', {'form': form})
        else:
            form = ReviewForm()
            return render(request, 'MyApp/review.html', {'form': form})
    else:
        return HttpResponse('You must be either a Premium or a Regular Member to submit reviews')


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                current_login_time = str(datetime.datetime.now())
                request.session['last_login'] = current_login_time
                request.session.set_expiry(60 * 60)
                request.session['username'] = username
                request.session['status'] = Member.objects.get(username=username).status
                if 'bookid' not in request.session:  #
                    return HttpResponseRedirect(reverse('MyAppIADS:index'))
                else:
                    return chk_reviews(request, request.session.get('bookid'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'MyApp/login.html')


def register_member(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            form.save()
            msg = 'Successfully registered! Kindly log in'
            return render(request, 'MyApp/register.html', {'msg': msg})
        else:
            return render(request, 'MyApp/register.html', {'form': MemberForm()})
    else:
        form = MemberForm()
        return render(request, 'MyApp/register.html', {'form': form})


def chk_reviews(request, book_id):
    request.session['bookid'] = book_id
    if request.session.has_key('username'):
        B = get_object_or_404(Book, id=book_id)
        R = Review.objects.filter(book__id=B.id)
        if Member.username:
            # user = authenticate()
            if R:
                total = 0
                i = 0
                for r in R:
                    total += r.rating
                    i += 1
                ave = total / i
                return render(request, 'MyApp/checkreviews.html',
                              {'review': R, 'Book': B, 'average': ave, 'total': total, 'count': i})
            else:
                return HttpResponse('There are no reviews')
        else:
            return HttpResponse('You are not a registered member')
    else:
        bookid = request.session.get('bookid')
        return render(request, 'MyApp/login.html', {'book': bookid})


def checkreviews(request):
    booklist = Book.objects.all().order_by('pk')[:10]
    return render(request, 'MyApp/chk_reviews.html', {'booklist': booklist})


def loginpage(request):
    return render(request,'MyApp/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('MyAppIADS:index'))


@login_required
def myorders(request):
    if Member.username:
        order = Order.objects.filter(member__username=request.user.username)
        return render(request, 'MyApp/myorder.html', {'order': order})
    else:
        return HttpResponse('You are not a registered member')

MyAppIADS/templates/MyApp/UserRatings.html
{% extends 'myapp/base0.html' %}

{% block body_block %}
    <h1>The Top 5 Books From User Ratings are:</h1>
    <b> Book Rating and Title are: </b>
    {% for r in Rating %}
        <ol>
        {% for x in r %}
        {{ x }}
        {% endfor %}
        </ol>
    {% endfor %}
{% endblock %}

MyAppIADS/templates/MyApp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>eBook App</title>
</head>
<body>

<h1>This is an eBook App </h1>
<p><a href="/MyAppIADS/">Back to the main</a></p>
</body>

</html>

MyAppIADS/templates/MyApp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'MyApp/style.css' %}" />
        <title>eBook APP - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
    {% if user.is_authenticated %}
        <div>
            <h1>{% block myhdg %}Hello {{ user.first_name }} {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li class="hbar1"><a href="/MyAppIADS/about/">Find out about this site</a></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:index' %}">Click here to return to main page</a><br/></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:findbooks' %}">Click here to Find a book</a><br/></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:placeorder' %}">Click here to Place an Order</a><br/></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:my_order' %}">CLick her to check your Orders</a><br/></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:review' %}">Click here to leave a Review</a><br/></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:User_Ratings' %}">Top 5 Books</a><br/></li>
                <li class="hbar1"><a href = "{% url 'MyAppIADS:logout' %}">Logout</a><br/></li>

            </ul>
        </div>
    {% else %}
        <div>
        <h1 class="container">{% block myhdg1 %}Hello New User {% endblock %}</h1>
            <div class="container">{% block body_block1 %} Please Login or Sign up</div>
        </div>
        <div>
            <ul>
            <li class="hbar1"><a href="{% url 'MyAppIADS:login' %}"> Login</a></li>
            <li class="hbar1"><a href="{% url 'MyAppIADS:register_member' %}"> Sign Up</a></li>
            </ul>
        </div>
        <hr/>
         {% endblock %}
    {% endif %}
</body>
</html>

MyAppIADS/templates/MyApp/base0.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
	<head>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/4796e54c8b.js" crossorigin="anonymous"></script>

		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>A Bookstore</title>
		<meta name="description" content="">
		<meta name="keywords" content="None" />
		<meta name="author" content="Frank, Deepraj, Priyanka" />
		<link rel="shortcut icon" href="../MyApp/favicon.ico">
        {% block cssblock %}
		<link rel="stylesheet" type="text/css" href="{% static 'MyApp/default.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'MyApp/component.css' %}" />
		<script src={% static 'MyApp/modernizr.custom.js'%} ></script>
        {% endblock %}
	</head>
	<body>
		<div class="container">

			<header class="clearfix">
				<h1 style="color: #333333;font-weight: bolder">The Bookstore <span style="color: gray; font-weight: bold ">Welcome to Paradise of Books</span></h1>
			</header>
            {% if user.is_authenticated %}
                {% if user.member.image %}
                <div class="row" style="margin-left: 10%"> <div class="col-md-1"> <img src='{{ user.member.image.url }}' class="rounded-circle" style="height: 80px;width: 80px;"></div>
                 {% endif %}
                <div class="col-md-3"> <p style="padding-top: 22px"> Hello {{ user.first_name    }} </p></div></div>
            {% endif %}
			<div class="main" >

{#                <div class="text-center"><img class="img-rounded" src="{{ user.Member.image.url }}"></div>#}
                {% block middle %}
                <div class="side">
					<nav class="dr-menu">
						<div class="dr-trigger"><span class="dr-icon dr-icon-menu"></span><a class="dr-label" >Menu</a></div>
						<ul>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:checkreviews' %} ><label><i class="fas fa-book"></i></label> Check Reviews</a></li>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:placeorder' %}><label><i class="fas fa-shopping-cart"></i></label> Order</a></li>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:my_order' %}><label><i class="fas fa-shopping-cart"></i></label>My Orders</a></li>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:about_page' %}><label><i class="fas fa-info-circle"></i></label> About</a></li>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:review' %}><label><i class="fas fa-pen-square"></i></label> Write Review</a></li>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:findbooks' %}><label><i class="fas fa-search"></i></label> Find Books</a></li>
                            <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:User_Ratings' %}><label><i class="fas fa-poll"></i></label> Top 5 Books</a></li>
                            {% if user.is_authenticated %}
                                <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:logout' %}><label><i class="fas fa-sign-out-alt"></i></label> Logout</a></li>
                            {% else %}
                                <li style="padding: 10px;"><a class="dropdown-item" href={% url 'MyAppIADS:loginpage' %}><label><i class="fas fa-sign-out-alt"></i></label> Login/Register</a></li>

                            {% endif %}
                        </ul>
					</nav>
				</div>

                <div style="font-size: 15px;padding: 0 1em;margin: 0;line-height: 1.6;float: right;width: 70%;">
                {% block body_block %}
                {% endblock %}
                </div>
                {% endblock %}
                {% block back %}
                <a href={% url 'MyAppIADS:index' %} style="color:#333333">Back To Main Page</a>
                {% endblock %}
			</div>
		</div><!-- /container -->
		<script src={% static 'MyApp/ytmenu.js'%}></script>
	</body>
</html>

MyAppIADS/templates/MyApp/chk_reviews.html
{% extends 'myapp/base0.html' %}

{% block body_block %}
        <div class="row"><p style="font-size: 35px;"> Check Book Reviews</p></div>
        <div class="row">
        <ol>
            {% for book  in booklist %}
                <li > <a style="color: #333333" href="{% url 'MyAppIADS:chk_reviews' book_id=book.id %}">{{book.title}}</a> </li>
            {% endfor %}
        </ol>
        </div>


{% endblock %}

MyAppIADS/templates/MyApp/index.html
{% extends 'myapp/base0.html' %}

{% block middle %}
        <a class="leftdiv" style="text-decoration: none;" href={% url 'MyAppIADS:login' %}>
        Login
        </a>
        <a class="rightdiv" style="text-decoration: none;" href={% url 'MyAppIADS:register_member' %}>
        Signup
        </a>
{% endblock %}

MyAppIADS/templates/MyApp/index0.html
{% extends 'myapp/base0.html' %}

{% block body_block %}


    {% if booklist %}
        <h2>List of Books</h2>
        <ol style="font-size: 29px; color: gray">
            {% for book  in booklist %}
                <li> <a style="color: #555555" href="{% url 'MyAppIADS:detail' book_id=book.id %}">{{book.title}}</a> </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}
    {% if last_login %}
    <p style="color: #555555;" >Your last login was at {{ last_login }}</p>
    {% else %}
    <p style="color: #555555" >Your last login was more than a hour ago</p>
    {% endif %}

{% endblock %}
{% block back %}{% endblock %}

MyAppIADS/templates/MyApp/login.html
{% extends 'myapp/base0.html' %}

{% block middle %}


        <div class="container">
          <form action="{% url 'MyAppIADS:login' %}" method="post">
              {% csrf_token %}
            <div class="form-group row">
            <label for="inputText" class="col-sm-2 col-form-label">Username</label>
            <div class="col-sm-10">
            <input type="Text" class="form-control" name="username" placeholder="Username">
            </div>
            </div>
             <div class="form-group row">
                 <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
            <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            </div>
              <div class="form-group row">
                <div class="offset-sm-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
              </div>
          </form>
         <a href="{% url 'password_reset' %}" style="color: #333333">Forgot Password?</a>
        </div>
{% endblock %}

MyAppIADS/templates/MyApp/placeorder.html
{% extends 'myapp/base0.html' %}

{% block body_block %}

    <form action="{% url 'MyAppIADS:placeorder' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="row"><p style="font-size: 50px;">Order Books</p></div>
        <div class="row" style="margin-top: 5%">

            <div class="col-md-5"><label style="font-size: 30px">Books</label>{{ form.books }}</div>
            <div class="col-md-3"><label style="font-size: 30px">Member</label>{{ form.member }}</div>
            <div class="col-md-3"><label style="font-size: 30px">Order Type</label>{{ form.order_type }}</div>

        </div>
        <input type="submit" class="btn btn-primary btn-lg" name="submit2" value="Place order" style="margin-left: 42%;"/>
    </form>

{% endblock %}

MyAppIADS/templates/MyApp/register.html
    {% extends 'myapp/base0.html' %}
    {% block title %} Register page{% endblock %}
    {% block middle %}
	<br>
		{% if msg %}
		<div>
			<h4>{{ msg }}</h4>
		</div>
		{% endif %}

		<form class="form" method="post">
			{% csrf_token %}
			<div style="margin-left: 5%">
            {{ form.username.errors }}
            <div class="row"><label >Username</label>{{ form.username }}</div>
                {{ form.first_name.errors }}
            <div class="row"><label >First Name</label>{{ form.first_name }}</div>
                {{ form.last_name.errors }}
            <div class="row"><label >Last Name</label>{{ form.last_name }}</div><br/>
                {{ form.email.errors }}
            <div class="row"><label >Email</label>{{ form.email }}</div>
                {{ form.password1.errors }}
            <div class="row"><label >Password1 &nbsp;</label>{{ form.password1 }}</div><br/>
                {{ form.password2.errors }}
            <div class="row"><label >Password2 &nbsp;</label>{{ form.password2 }}</div>
			<button type="submit" class="btn btn-dark">Register</button>
            </div>
		</form>
		<p>
			<a href="{% url 'MyAppIADS:login' %}" style="color: #333333;font-size: 25px"> Already Registered? Sign In!</a>
		</p>

	{% endblock %}